TRANSI CON            1 
MOD 
** Alta transmissibilidade no layer 3 com barreiras 
1:51  1:27  3:3 = 1

 
 
TRANSK EQUALSI 
MOD 
1:51  1:28  2:3 = 1

 
TRANSJ EQUALSI 
 
** Falha 2 direção N-S situada a oeste 
** Falha       1 dir N-S situada a     oeste 
 
TRANSF  'F   1'      0.1000 
              11       3       1 IDIR+         11       4       1 IDIR+         11       5       1 IDIR+ 
              11       6       1 IDIR+         11       7       1 IDIR+         11       8       1 IDIR+ 
              11       9       1 IDIR+         12      10       1 IDIR+         12      11       1 IDIR+ 
              13      12       1 IDIR+         13      13       1 IDIR+         13      14       1 IDIR+ 
              14      15       1 IDIR+         17      16       1 IDIR+         22      17       1 IDIR+ 
              22      18       1 IDIR+         22      19       1 IDIR+         23      20       1 IDIR+ 
              23      21       1 IDIR+         24      22       1 IDIR+         24      23       1 IDIR+ 
              24      24       1 IDIR+         24      25       1 IDIR+         11       3       2 IDIR+ 
              11       4       2 IDIR+ 
              11       5       2 IDIR+         11       6       2 IDIR+         11       7       2 IDIR+ 
              11       8       2 IDIR+         11       9       2 IDIR+         12      10       2 IDIR+ 
              12      11       2 IDIR+         13      12       2 IDIR+         13      13       2 IDIR+ 
              13      14       2 IDIR+         14      15       2 IDIR+         17      16       2 IDIR+ 
              22      17       2 IDIR+         22      18       2 IDIR+         22      19       2 IDIR+ 
              23      20       2 IDIR+         23      21       2 IDIR+         24      22       2 IDIR+ 
              24      23       2 IDIR+         24      24       2 IDIR+ 
              24      25       2 IDIR+         11       3       3 IDIR+ 
              11       4       3 IDIR+         11       5       3 IDIR+         11       6       3 IDIR+ 
              11       7       3 IDIR+         11       8       3 IDIR+         11       9       3 IDIR+ 
              12      10       3 IDIR+         12      11       3 IDIR+         13      12       3 IDIR+ 
              13      13       3 IDIR+         13      14       3 IDIR+         14      15       3 IDIR+ 
              17      16       3 IDIR+         22      17       3 IDIR+         22      18       3 IDIR+ 
              22      19       3 IDIR+         23      20       3 IDIR+         23      21       3 IDIR+ 
              24      22       3 IDIR+         24      23       3 IDIR+         24      24       3 IDIR+ 
              24      25       3 IDIR+ 
              11       3       4 IDIR+         11       4       4 IDIR+         11       5       4 IDIR+ 
              11       6       4 IDIR+         11       7       4 IDIR+         11       8       4 IDIR+ 
              11       9       4 IDIR+         12      10       4 IDIR+         12      11       4 IDIR+ 
              13      12       4 IDIR+         13      13       4 IDIR+         13      14       4 IDIR+ 
              14      15       4 IDIR+         17      16       4 IDIR+         22      17       4 IDIR+ 
              22      18       4 IDIR+         22      19       4 IDIR+         23      20       4 IDIR+ 
              23      21       4 IDIR+         24      22       4 IDIR+         24      23       4 IDIR+ 
              24      24       4 IDIR+ 
              24      25       4 IDIR+         11       3       5 IDIR+         11       4       5 IDIR+ 
              11       5       5 IDIR+         11       6       5 IDIR+         11       7       5 IDIR+ 
              11       8       5 IDIR+         11       9       5 IDIR+         12      10       5 IDIR+ 
              12      11       5 IDIR+         13      12       5 IDIR+         13      13       5 IDIR+ 
              13      14       5 IDIR+         14      15       5 IDIR+         17      16       5 IDIR+ 
              22      17       5 IDIR+         22      18       5 IDIR+         22      19       5 IDIR+ 
              23      20       5 IDIR+         23      21       5 IDIR+         24      22       5 IDIR+ 
              24      23       5 IDIR+         24      24       5 IDIR+ 
              24      25       5 IDIR+         11       3       6 IDIR+ 
              11       4       6 IDIR+         11       5       6 IDIR+         11       6       6 IDIR+ 
              11       7       6 IDIR+         11       8       6 IDIR+         11       9       6 IDIR+ 
              12      10       6 IDIR+         12      11       6 IDIR+         13      12       6 IDIR+ 
              13      13       6 IDIR+         13      14       6 IDIR+         14      15       6 IDIR+ 
              17      16       6 IDIR+         22      17       6 IDIR+         22      18       6 IDIR+ 
              22      19       6 IDIR+         23      20       6 IDIR+         23      21       6 IDIR+ 
              24      22       6 IDIR+         24      23       6 IDIR+         24      24       6 IDIR+ 
              24      25       6 IDIR+ 
              12       9       1 JDIR+         13      11       1 JDIR+         14      14       1 JDIR+ 
              22      16       1 JDIR+         21      16       1 JDIR+         20      16       1 JDIR+ 
              19      16       1 JDIR+         18      16       1 JDIR+         17      15       1 JDIR+ 
              16      15       1 JDIR+         15      15       1 JDIR+         23      19       1 JDIR+ 
              24      21       1 JDIR+         12       9       2 JDIR+ 
              13      11       2 JDIR+         14      14       2 JDIR+         22      16       2 JDIR+ 
              21      16       2 JDIR+         20      16       2 JDIR+         19      16       2 JDIR+ 
              18      16       2 JDIR+         17      15       2 JDIR+         16      15       2 JDIR+ 
              15      15       2 JDIR+         23      19       2 JDIR+         24      21       2 JDIR+ 
              12       9       3 JDIR+         13      11       3 JDIR+ 
              14      14       3 JDIR+         22      16       3 JDIR+ 
              21      16       3 JDIR+         20      16       3 JDIR+         19      16       3 JDIR+ 
              18      16       3 JDIR+ 
              17      15       3 JDIR+         16      15       3 JDIR+         15      15       3 JDIR+ 
              23      19       3 JDIR+         24      21       3 JDIR+  
              12       9       4 JDIR+         13      11       4 JDIR+         14      14       4 JDIR+  
              22      16       4 JDIR+ 
              21      16       4 JDIR+         20      16       4 JDIR+         19      16       4 JDIR+ 
              18      16       4 JDIR+         17      15       4 JDIR+ 
              16      15       4 JDIR+         15      15       4 JDIR+         23      19       4 JDIR+ 
              24      21       4 JDIR+         12       9       5 JDIR+ 
              13      11       5 JDIR+         14      14       5 JDIR+         22      16       5 JDIR+ 
              21      16       5 JDIR+         20      16       5 JDIR+         19      16       5 JDIR+ 
              18      16       5 JDIR+         17      15       5 JDIR+         16      15       5 JDIR+ 
              15      15       5 JDIR+         23      19       5 JDIR+         24      21       5 JDIR+ 
              12       9       6 JDIR+         13      11       6 JDIR+ 
              14      14       6 JDIR+         22      16       6 JDIR+ 
              21      16       6 JDIR+         20      16       6 JDIR+         19      16       6 JDIR+ 
              18      16       6 JDIR+ 
              17      15       6 JDIR+         16      15       6 JDIR+         15      15       6 JDIR+ 
              23      19       6 JDIR+         24      21       6 JDIR+     
 
  
** Falha 3 direção N-S situada a leste   
 
 

 
 
** Falha 3 direção N-S situada a leste  
** Falha 2 direção N-S situada a leste 
 
TRANSF 'F   2'   0.000 
              31       3       1 IDIR+         31       4       1 IDIR+         31       5       1 IDIR+ 
              31       6       1 IDIR+         31       7       1 IDIR+         33       8       1 IDIR+ 
              33       9       1 IDIR+         33      10       1 IDIR+         33      11       1 IDIR+ 
              35      12       1 IDIR+         35      13       1 IDIR+         35      14       1 IDIR+ 
              35      15       1 IDIR+         37      16       1 IDIR+         37      17       1 IDIR+ 
              37      18       1 IDIR+         39      19       1 IDIR+         39      20       1 IDIR+ 
              39      21       1 IDIR+         39      22       1 IDIR+         39      23       1 IDIR+ 
              39      24       1 IDIR+         39      25       1 IDIR+         31       3       2 IDIR+ 
              31       4       2 IDIR+         31       5       2 IDIR+         31       6       2 IDIR+ 
              31       7       2 IDIR+         33       8       2 IDIR+         33       9       2 IDIR+ 
              33      10       2 IDIR+         33      11       2 IDIR+         35      12       2 IDIR+ 
              35      13       2 IDIR+         35      14       2 IDIR+         35      15       2 IDIR+ 
              37      16       2 IDIR+         37      17       2 IDIR+         37      18       2 IDIR+ 
              39      19       2 IDIR+         39      20       2 IDIR+         39      21       2 IDIR+ 
              39      22       2 IDIR+         39      23       2 IDIR+         39      24       2 IDIR+ 
              39      25       2 IDIR+         31       3       3 IDIR+         31       4       3 IDIR+ 
              31       5       3 IDIR+         31       6       3 IDIR+         31       7       3 IDIR+ 
              33       8       3 IDIR+         33       9       3 IDIR+         33      10       3 IDIR+ 
              33      11       3 IDIR+         35      12       3 IDIR+         35      13       3 IDIR+ 
              35      14       3 IDIR+         35      15       3 IDIR+         37      16       3 IDIR+ 
              37      17       3 IDIR+         37      18       3 IDIR+         39      19       3 IDIR+ 
              39      20       3 IDIR+         39      21       3 IDIR+         39      22       3 IDIR+ 
              39      23       3 IDIR+         39      24       3 IDIR+         39      25       3 IDIR+ 
              31       3       4 IDIR+         31       4       4 IDIR+         31       5       4 IDIR+ 
              31       6       4 IDIR+         31       7       4 IDIR+         33       8       4 IDIR+ 
              33       9       4 IDIR+         33      10       4 IDIR+         33      11       4 IDIR+ 
              35      12       4 IDIR+         35      13       4 IDIR+         35      14       4 IDIR+ 
              35      15       4 IDIR+         37      16       4 IDIR+         37      17       4 IDIR+ 
              37      18       4 IDIR+         39      19       4 IDIR+         39      20       4 IDIR+ 
              39      21       4 IDIR+         39      22       4 IDIR+         39      23       4 IDIR+ 
              39      24       4 IDIR+         39      25       4 IDIR+         31       3       5 IDIR+ 
              31       4       5 IDIR+         31       5       5 IDIR+         31       6       5 IDIR+ 
              31       7       5 IDIR+         33       8       5 IDIR+         33       9       5 IDIR+ 
              33      10       5 IDIR+         33      11       5 IDIR+         35      12       5 IDIR+ 
              35      13       5 IDIR+         35      14       5 IDIR+         35      15       5 IDIR+ 
              37      16       5 IDIR+         37      17       5 IDIR+         37      18       5 IDIR+ 
              39      19       5 IDIR+         39      20       5 IDIR+         39      21       5 IDIR+ 
              39      22       5 IDIR+         39      23       5 IDIR+         39      24       5 IDIR+ 
              39      25       5 IDIR+         31       3       6 IDIR+         31       4       6 IDIR+ 
              31       5       6 IDIR+         31       6       6 IDIR+         31       7       6 IDIR+ 
              33       8       6 IDIR+         33       9       6 IDIR+         33      10       6 IDIR+ 
              33      11       6 IDIR+         35      12       6 IDIR+         35      13       6 IDIR+ 
              35      14       6 IDIR+         35      15       6 IDIR+         37      16       6 IDIR+ 
              37      17       6 IDIR+         37      18       6 IDIR+         39      19       6 IDIR+ 
              39      20       6 IDIR+         39      21       6 IDIR+         39      22       6 IDIR+ 
              39      23       6 IDIR+         39      24       6 IDIR+         39      25       6 IDIR+ 
              33       7       1 JDIR+         32       7       1 JDIR+         35      11       1 JDIR+ 
              34      11       1 JDIR+         37      15       1 JDIR+         36      15       1 JDIR+ 
              39      18       1 JDIR+         38      18       1 JDIR+         33       7       2 JDIR+ 
              32       7       2 JDIR+         35      11       2 JDIR+         34      11       2 JDIR+ 
              37      15       2 JDIR+         36      15       2 JDIR+         39      18       2 JDIR+ 
              38      18       2 JDIR+         33       7       3 JDIR+         32       7       3 JDIR+ 
              35      11       3 JDIR+         34      11       3 JDIR+         37      15       3 JDIR+ 
              36      15       3 JDIR+         39      18       3 JDIR+         38      18       3 JDIR+ 
              33       7       4 JDIR+         32       7       4 JDIR+         35      11       4 JDIR+ 
              34      11       4 JDIR+         37      15       4 JDIR+         36      15       4 JDIR+ 
              39      18       4 JDIR+         38      18       4 JDIR+         33       7       5 JDIR+ 
              32       7       5 JDIR+         35      11       5 JDIR+         34      11       5 JDIR+ 
              37      15       5 JDIR+         36      15       5 JDIR+         39      18       5 JDIR+ 
              38      18       5 JDIR+         33       7       6 JDIR+         32       7       6 JDIR+ 
              35      11       6 JDIR+         34      11       6 JDIR+         37      15       6 JDIR+ 
              36      15       6 JDIR+         39      18       6 JDIR+         38      18       6 JDIR+ 
 
  
** Falha 1 direção L-O  
 

 
 
** Falha 1 direção L-O 
** Falha 3 direção L-O 
 
TRANSF 'F   3'   1.000 
             28     11      1 IDIR+      26     12      1 IDIR+      24     13      1 IDIR+ 
             21     14      1 IDIR+      17     15      1 IDIR+      14     16      1 IDIR+ 
             10     17      1 IDIR+      10     18      1 IDIR+      28     11      2 IDIR+ 
             26     12      2 IDIR+      24     13      2 IDIR+      21     14      2 IDIR+ 
             17     15      2 IDIR+      14     16      2 IDIR+      10     17      2 IDIR+ 
             10     18      2 IDIR+      28     11      3 IDIR+      26     12      3 IDIR+ 
             24     13      3 IDIR+      21     14      3 IDIR+      17     15      3 IDIR+ 
             14     16      3 IDIR+      10     17      3 IDIR+      10     18      3 IDIR+ 
             28     11      4 IDIR+      26     12      4 IDIR+      24     13      4 IDIR+ 
             21     14      4 IDIR+      17     15      4 IDIR+      14     16      4 IDIR+ 
             10     17      4 IDIR+      10     18      4 IDIR+      28     11      5 IDIR+ 
             26     12      5 IDIR+      24     13      5 IDIR+      21     14      5 IDIR+ 
             17     15      5 IDIR+      14     16      5 IDIR+      10     17      5 IDIR+ 
             10     18      5 IDIR+      28     11      6 IDIR+      26     12      6 IDIR+ 
             24     13      6 IDIR+      21     14      6 IDIR+      17     15      6 IDIR+ 
             14     16      6 IDIR+      10     17      6 IDIR+      10     18      6 IDIR+ 
             33     10      1 JDIR+ 
             32     10      1 JDIR+      31     10      1 JDIR+      30     10      1 JDIR+ 
             29     10      1 JDIR+      28     11      1 JDIR+      27     11      1 JDIR+ 
             26     12      1 JDIR+      25     12      1 JDIR+      24     13      1 JDIR+ 
             23     13      1 JDIR+      22     13      1 JDIR+      21     14      1 JDIR+ 
             20     14      1 JDIR+      19     14      1 JDIR+      18     14      1 JDIR+ 
             17     15      1 JDIR+      16     15      1 JDIR+      15     15      1 JDIR+ 
             14     16      1 JDIR+      13     16      1 JDIR+      12     16      1 JDIR+ 
             11     16      1 JDIR+      33     10      2 JDIR+ 
             32     10      2 JDIR+      31     10      2 JDIR+ 
             30     10      2 JDIR+      29     10      2 JDIR+      28     11      2 JDIR+ 
             27     11      2 JDIR+      26     12      2 JDIR+      25     12      2 JDIR+ 
             24     13      2 JDIR+      23     13      2 JDIR+      22     13      2 JDIR+ 
             21     14      2 JDIR+      20     14      2 JDIR+      19     14      2 JDIR+ 
             18     14      2 JDIR+      17     15      2 JDIR+      16     15      2 JDIR+ 
             15     15      2 JDIR+      14     16      2 JDIR+      13     16      2 JDIR+ 
             12     16      2 JDIR+      11     16      2 JDIR+ 
             33     10      3 JDIR+      32     10      3 JDIR+ 
             31     10      3 JDIR+      30     10      3 JDIR+      29     10      3 JDIR+ 
             28     11      3 JDIR+      27     11      3 JDIR+      26     12      3 JDIR+ 
             25     12      3 JDIR+      24     13      3 JDIR+      23     13      3 JDIR+ 
             22     13      3 JDIR+      21     14      3 JDIR+      20     14      3 JDIR+ 
             19     14      3 JDIR+      18     14      3 JDIR+      17     15      3 JDIR+ 
             16     15      3 JDIR+      15     15      3 JDIR+      14     16      3 JDIR+ 
             13     16      3 JDIR+      12     16      3 JDIR+      11     16      3 JDIR+ 
             33     10      4 JDIR+ 
             32     10      4 JDIR+      31     10      4 JDIR+      30     10      4 JDIR+ 
             29     10      4 JDIR+      28     11      4 JDIR+      27     11      4 JDIR+ 
             26     12      4 JDIR+      25     12      4 JDIR+      24     13      4 JDIR+ 
             23     13      4 JDIR+      22     13      4 JDIR+      21     14      4 JDIR+ 
             20     14      4 JDIR+      19     14      4 JDIR+      18     14      4 JDIR+ 
             17     15      4 JDIR+      16     15      4 JDIR+      15     15      4 JDIR+ 
             14     16      4 JDIR+      13     16      4 JDIR+      12     16      4 JDIR+ 
             11     16      4 JDIR+ 
             33     10      5 JDIR+      32     10      5 JDIR+      31     10      5 JDIR+ 
             30     10      5 JDIR+      29     10      5 JDIR+      28     11      5 JDIR+ 
             27     11      5 JDIR+      26     12      5 JDIR+      25     12      5 JDIR+ 
             24     13      5 JDIR+      23     13      5 JDIR+      22     13      5 JDIR+ 
             21     14      5 JDIR+      20     14      5 JDIR+      19     14      5 JDIR+ 
             18     14      5 JDIR+      17     15      5 JDIR+      16     15      5 JDIR+ 
             15     15      5 JDIR+      14     16      5 JDIR+      13     16      5 JDIR+ 
             12     16      5 JDIR+      11     16      5 JDIR+ 
             33     10      6 JDIR+      32     10      6 JDIR+ 
             31     10      6 JDIR+      30     10      6 JDIR+      29     10      6 JDIR+ 
             28     11      6 JDIR+      27     11      6 JDIR+      26     12      6 JDIR+ 
             25     12      6 JDIR+      24     13      6 JDIR+      23     13      6 JDIR+ 
             22     13      6 JDIR+      21     14      6 JDIR+      20     14      6 JDIR+ 
             19     14      6 JDIR+      18     14      6 JDIR+      17     15      6 JDIR+ 
             16     15      6 JDIR+      15     15      6 JDIR+      14     16      6 JDIR+ 
             13     16      6 JDIR+      12     16      6 JDIR+      11     16      6 JDIR+ 
